"""empty message

Revision ID: 3d52176ea6f4
Revises: None
Create Date: 2015-05-11 18:25:57.860109

"""

# revision identifiers, used by Alembic.
revision = '3d52176ea6f4'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('authenticated', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('email')
    )
    ### end Alembic commands ###
